  
namespace: "lyr"
name: "Opendistro Collection"
version: "0.0.4"
readme: "README.md"
authors:
  - "Lyr"
description: "Collection of Opendistro roles"
license:
  - "MIT"
tags:
  - linux
  - development
  - opendistro
  - collection
  - kibana
  - elasticsearch
  - aws
repository: "https://www.github.com/Lyr/ansible-role-opendistro"
homepage: "https://www.github.com/Lyr/ansible-role-opendistro"
documentation: "https://www.github.com/Lyr/ansible-role-opendistro"
issues: "https://www.github.com/Lyr/ansible-role-opendistro/issues"