---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e 
  yamllint -c molecule/default/yaml-lint.yml
platforms:
  - name: instance
    image: centos:7
    #image: debian:buster
    #image: debian:jessie
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    enabled: true
    options:
      x:
        - ANSIBLE0011
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - verify
verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    # show which tests where executed in test output
    v: 1