---
opendistroforelasticsearch_user: "{{ __opendistroforelasticsearch_user }}"
opendistroforelasticsearch_group: "{{ __opendistroforelasticsearch_group }}"
opendistroforelasticsearch_log_dir: "{{ __opendistroforelasticsearch_log_dir }}"
opendistroforelasticsearch_db_dir: "{{ __opendistroforelasticsearch_db_dir }}"
opendistroforelasticsearch_scripts_dir: "{{ __opendistroforelasticsearch_scripts_dir }}"
opendistroforelasticsearch_plugins_dir: "{{ __opendistroforelasticsearch_plugins_dir }}"
opendistroforelasticsearch_plugin_command: "{{ __opendistroforelasticsearch_plugin_command }}"
opendistroforelasticsearch_plugins: []
opendistroforelasticsearch_service: "{{ __opendistroforelasticsearch_service }}"
opendistroforelasticsearch_package: "{{ __opendistroforelasticsearch_package }}"
opendistroforelasticsearch_extra_packages: []
opendistroforelasticsearch_conf_dir: "{{ __opendistroforelasticsearch_conf_dir }}"
opendistroforelasticsearch_jvm_options: ""
opendistroforelasticsearch_conf_file: "{{ opendistroforelasticsearch_conf_dir }}/elasticsearch.yml"
opendistroforelasticsearch_flags: ""
opendistroforelasticsearch_config: ""
opendistroforelasticsearch_http_port: 9200
opendistroforelasticsearch_java_home: "{{ __opendistroforelasticsearch_java_home }}"
opendistroforelasticsearch_extra_plugin_files: []
opendistroforelasticsearch_include_role_x509_certificate: yes
opendistroforelasticsearch_redhat_repo_url: "https://d3g5vo6xdbdb9a.cloudfront.net/yum/opendistroforelasticsearch-artifacts.repo"

es_use_repository: false
es_version: "7.3.2"
es_major_version: "7.x"
es_repo_url: https://artifacts.elastic.co/packages/oss-{{ es_major_version }}/yum
es_repo_name: "{{ es_major_version }}"
