---
galaxy_info:
  author: Lyr
  description: role to provide an opendistro cluster (with or not kibana)
  company: Yl-Co
  license: MIT

  min_ansible_version: 2.9
  platforms:
    - name: Debian
      versions:
        - all

  galaxy_tags: ["opendistro", "elasticsearch", "aws", "kibana"]

dependencies: [setup_repo]
collections: [ 'opendistro' ]

