name: Publish Ansible Galaxy

on: [push]
  # release:
  #   types:
  #     - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade ansible
        pip install ansible docker 'molecule[docker]'
    - name: Molecule test
      run: |
        cd roles/opendistro_elasticsearch/ && molecule test
    - name: Deploy Ansible Galaxy Collection
      uses: artis3n/ansible_galaxy_collection@v1.0.10
      with:
        api_key: ${{ secrets.galaxy_api_key }}
        galaxy_config_file: galaxy.yml
