name: Publish Ansible Galaxy

on: [push]
  # release:
  #   types:
  #     - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade ansible
    - name: Report Ansible version
      run: ansible --version
    - name: Move project to Ansible-required location
      run: |
        cd roles/opendistro_elasticsearch
    - name: Molecule
      uses: gofrolist/molecule-action@master
      with:
        molecule_options: --debug --base-config molecule/_shared/base.yml
        molecule_command: test
    - name: ansible-lint
      uses: ansible/ansible-lint-action@v4.1.0.post0
      with:
        targets: |
          molecule/default/playbook.yml
    - name: Deploy Ansible Galaxy Collection
      uses: artis3n/ansible_galaxy_collection@v1.0.10
      with:
        api_key: ${{ secrets.galaxy_api_key }}
        galaxy_config_file: galaxy.yml
