name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ansible-lint
      uses: ansible/ansible-lint-action@v4.1.0.post0
      with:
        targets: 
          - roles/opendistro_elasticsearch/tests/test.yml
    - name: Deploy Ansible Galaxy Collection
      uses: artis3n/ansible_galaxy_collection@v1.0.10
      with:
        api_key: ${{ secrets.galaxy_api_key }}
        galaxy_config_file: galaxy.yml
